### ISSUE TITLE
Le flux fantôme du donjon de naheulbeuk

### ISSUE THREAD

**Issue by PhilGoud** [PodShows/podcloud-feeds#6]
Si on demande rien, on a le flux du donjon de naheulbeuk :

{
podcastForFeedWithIdentifier(identifier: "") {
  identifier,
  feed_url,
  items {
    title
    url
    author
    ...on Episode{
      enclosure {
        url
      }
    }
  }
}
}

**Comment by PofMagicfingers** [comment]
trouvé ! 
Dans la requête vers MongoDB je cherche les podcasts qui ont soit :
- `identifier` dans le champ identifier (logique)
- `identifier` dans le champ `custom_domain`
- `identifier` dans le l'historique des identifier ( `_slugs` )

Le soucis c'est que si `identifier = ""`, bah vu que `custom_domain = ""` dans l'énorme majorité des cas, ça retourne le premier podcast dispo. Faut simplement interdire la requête avec un identifier vide, parce que de base ça n'a pas de sens.
